# Generated by Django 3.2.5 on 2021-08-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(max_length=128)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('surname', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('series', models.CharField(blank=True, max_length=64, null=True)),
                ('book_format', models.CharField(choices=[('audio', 'Audiobook'), ('ebook', 'Ebook'), ('print', 'Print')], default='print', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('un_code', models.IntegerField(default=-99, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=32)),
                ('phone', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office', to='master.address')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=120, null=True)),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='master.countries')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='master.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=16)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loaned', models.DateField()),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.users')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.address')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=16)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='master.provinces')),
            ],
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.books')),
            ],
        ),
        migrations.CreateModel(
            name='BooksAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.authors')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.books')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.cities'),
        ),
    ]
