# Generated by Django 3.2.5 on 2021-08-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(to='master.Authors'),
        ),
    ]
