# Generated by Django 3.2.5 on 2021-08-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_books_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksAuthors',
        ),
    ]
