# Generated by Django 3.2.5 on 2021-08-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_delete_booksauthors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=64)),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bookstatus',
            name='owned',
        ),
        migrations.AddField(
            model_name='books',
            name='owned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookstatus',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookstatus',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='bookstatus',
            name='book',
        ),
        migrations.AddField(
            model_name='bookstatus',
            name='book',
            field=models.ManyToManyField(to='master.Books'),
        ),
    ]
