# Generated by Django 3.2.5 on 2021-08-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210827_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookStatus',
        ),
        migrations.DeleteModel(
            name='Loans',
        ),
    ]
